spring:
     #thymeleaf模板配置
     thymeleaf:
          prefix: classpath:/templates/
          suffix: .html
          mode: HTML
          encoding: UTF-8
          #热部署文件，页面不产生缓存，及时更新
          cache: false
     # 上传文件配置
     servlet:
          multipart:
               enabled: true
               file-size-threshold: 0
               location: D:/Document_Storm_Upload_File
               max-file-size: 10MB
               max-request-size: 11MB
               resolve-lazily: false

server:
     port: 9090
     tomcat:
          uri-encoding: utf-8
     servlet:
          session:
               timeout: 30m